# -*- coding: utf-8 -*-
# Generated by Django 1.9.1 on 2016-01-04 16:02
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Bar',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=128, unique=True)),
                ('direccion', models.CharField(max_length=128)),
                ('numero_visita', models.IntegerField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name='Tapa',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=128)),
                ('votos', models.IntegerField(default=0)),
                ('bar', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='bares.Bar')),
            ],
        ),
    ]
