# -*- coding: utf-8 -*-
# Generated by Django 1.9.1 on 2016-01-13 16:02
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bares', '0002_bar_slug'),
    ]

    operations = [
        migrations.AddField(
            model_name='tapa',
            name='imagen',
            field=models.ImageField(blank=True, upload_to='imagenes_tapas'),
        ),
    ]
